apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-backend-secret
  namespace: {{ include "beacon.namespace" . }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
type: Opaque
stringData:
    {{- range $key, $value := .Values.backend.env }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
