"""Country -> continent lookup, keyed by lowercased country name (and common
aliases/abbreviations), for the Account Sourcing headquarters-continent
filter.

There is no continent (or even structured country) field anywhere in the
data — only the free-text `Company.headquarters` field (e.g. "Wrocław,
Poland"). The country is parsed from that text (see
`_headquarters_country_expr` in account_sourcing.py), then looked up here.
Because the underlying text is enrichment-sourced and unstandardized, this
mapping is deliberately generous with aliases ("USA", "US", "United States
of America" all resolve the same way) but can never be exhaustive — any
country string that doesn't match anything here falls into the "other"
bucket rather than silently vanishing from every continent filter.
"""

ASIA = "asia"
AFRICA = "africa"
EUROPE = "europe"
AUSTRALIA = "australia"
NORTH_AMERICA = "north_america"
SOUTH_AMERICA = "south_america"
OTHER = "other"

HEADQUARTERS_CONTINENT_LABELS = {
    ASIA: "Asia",
    AFRICA: "Africa",
    EUROPE: "Europe",
    AUSTRALIA: "Australia",
    NORTH_AMERICA: "North America",
    SOUTH_AMERICA: "South America",
    OTHER: "Other / Unrecognized",
}

# Lowercased country name/alias -> continent key. Aliases are listed
# immediately after their canonical name.
COUNTRY_TO_CONTINENT: dict[str, str] = {
    # Asia
    "afghanistan": ASIA,
    "armenia": ASIA,
    "azerbaijan": ASIA,
    "bahrain": ASIA,
    "bangladesh": ASIA,
    "bhutan": ASIA,
    "brunei": ASIA,
    "cambodia": ASIA,
    "china": ASIA,
    "people's republic of china": ASIA,
    "prc": ASIA,
    "cyprus": ASIA,
    "georgia": ASIA,
    "hong kong": ASIA,
    "india": ASIA,
    "indonesia": ASIA,
    "iran": ASIA,
    "iraq": ASIA,
    "israel": ASIA,
    "japan": ASIA,
    "jordan": ASIA,
    "kazakhstan": ASIA,
    "kuwait": ASIA,
    "kyrgyzstan": ASIA,
    "laos": ASIA,
    "lebanon": ASIA,
    "macau": ASIA,
    "malaysia": ASIA,
    "maldives": ASIA,
    "mongolia": ASIA,
    "myanmar": ASIA,
    "burma": ASIA,
    "nepal": ASIA,
    "north korea": ASIA,
    "oman": ASIA,
    "pakistan": ASIA,
    "palestine": ASIA,
    "philippines": ASIA,
    "qatar": ASIA,
    "saudi arabia": ASIA,
    "singapore": ASIA,
    "south korea": ASIA,
    "korea": ASIA,
    "sri lanka": ASIA,
    "syria": ASIA,
    "taiwan": ASIA,
    "tajikistan": ASIA,
    "thailand": ASIA,
    "timor-leste": ASIA,
    "turkey": ASIA,
    "turkiye": ASIA,
    "turkmenistan": ASIA,
    "uae": ASIA,
    "united arab emirates": ASIA,
    "uzbekistan": ASIA,
    "vietnam": ASIA,
    "yemen": ASIA,

    # Africa
    "algeria": AFRICA,
    "angola": AFRICA,
    "benin": AFRICA,
    "botswana": AFRICA,
    "burkina faso": AFRICA,
    "burundi": AFRICA,
    "cabo verde": AFRICA,
    "cape verde": AFRICA,
    "cameroon": AFRICA,
    "central african republic": AFRICA,
    "chad": AFRICA,
    "comoros": AFRICA,
    "congo": AFRICA,
    "democratic republic of the congo": AFRICA,
    "drc": AFRICA,
    "djibouti": AFRICA,
    "egypt": AFRICA,
    "equatorial guinea": AFRICA,
    "eritrea": AFRICA,
    "eswatini": AFRICA,
    "swaziland": AFRICA,
    "ethiopia": AFRICA,
    "gabon": AFRICA,
    "gambia": AFRICA,
    "ghana": AFRICA,
    "guinea": AFRICA,
    "guinea-bissau": AFRICA,
    "ivory coast": AFRICA,
    "cote d'ivoire": AFRICA,
    "kenya": AFRICA,
    "lesotho": AFRICA,
    "liberia": AFRICA,
    "libya": AFRICA,
    "madagascar": AFRICA,
    "malawi": AFRICA,
    "mali": AFRICA,
    "mauritania": AFRICA,
    "mauritius": AFRICA,
    "morocco": AFRICA,
    "mozambique": AFRICA,
    "namibia": AFRICA,
    "niger": AFRICA,
    "nigeria": AFRICA,
    "rwanda": AFRICA,
    "sao tome and principe": AFRICA,
    "senegal": AFRICA,
    "seychelles": AFRICA,
    "sierra leone": AFRICA,
    "somalia": AFRICA,
    "south africa": AFRICA,
    "south sudan": AFRICA,
    "sudan": AFRICA,
    "tanzania": AFRICA,
    "togo": AFRICA,
    "tunisia": AFRICA,
    "uganda": AFRICA,
    "zambia": AFRICA,
    "zimbabwe": AFRICA,

    # Europe
    "albania": EUROPE,
    "andorra": EUROPE,
    "austria": EUROPE,
    "belarus": EUROPE,
    "belgium": EUROPE,
    "bosnia and herzegovina": EUROPE,
    "bosnia": EUROPE,
    "bulgaria": EUROPE,
    "croatia": EUROPE,
    "czech republic": EUROPE,
    "czechia": EUROPE,
    "denmark": EUROPE,
    "estonia": EUROPE,
    "finland": EUROPE,
    "france": EUROPE,
    "germany": EUROPE,
    "greece": EUROPE,
    "hungary": EUROPE,
    "iceland": EUROPE,
    "ireland": EUROPE,
    "italy": EUROPE,
    "kosovo": EUROPE,
    "latvia": EUROPE,
    "liechtenstein": EUROPE,
    "lithuania": EUROPE,
    "luxembourg": EUROPE,
    "malta": EUROPE,
    "moldova": EUROPE,
    "monaco": EUROPE,
    "montenegro": EUROPE,
    "netherlands": EUROPE,
    "the netherlands": EUROPE,
    "holland": EUROPE,
    "north macedonia": EUROPE,
    "macedonia": EUROPE,
    "norway": EUROPE,
    "poland": EUROPE,
    "portugal": EUROPE,
    "romania": EUROPE,
    "russia": EUROPE,
    "russian federation": EUROPE,
    "san marino": EUROPE,
    "serbia": EUROPE,
    "slovakia": EUROPE,
    "slovenia": EUROPE,
    "spain": EUROPE,
    "sweden": EUROPE,
    "switzerland": EUROPE,
    "ukraine": EUROPE,
    "united kingdom": EUROPE,
    "uk": EUROPE,
    "great britain": EUROPE,
    "england": EUROPE,
    "scotland": EUROPE,
    "wales": EUROPE,
    "northern ireland": EUROPE,
    "vatican city": EUROPE,

    # Australia / Oceania
    "australia": AUSTRALIA,
    "fiji": AUSTRALIA,
    "kiribati": AUSTRALIA,
    "marshall islands": AUSTRALIA,
    "micronesia": AUSTRALIA,
    "nauru": AUSTRALIA,
    "new zealand": AUSTRALIA,
    "palau": AUSTRALIA,
    "papua new guinea": AUSTRALIA,
    "samoa": AUSTRALIA,
    "solomon islands": AUSTRALIA,
    "tonga": AUSTRALIA,
    "tuvalu": AUSTRALIA,
    "vanuatu": AUSTRALIA,

    # North America (includes Central America + Caribbean)
    "antigua and barbuda": NORTH_AMERICA,
    "bahamas": NORTH_AMERICA,
    "barbados": NORTH_AMERICA,
    "belize": NORTH_AMERICA,
    "canada": NORTH_AMERICA,
    "costa rica": NORTH_AMERICA,
    "cuba": NORTH_AMERICA,
    "dominica": NORTH_AMERICA,
    "dominican republic": NORTH_AMERICA,
    "el salvador": NORTH_AMERICA,
    "grenada": NORTH_AMERICA,
    "guatemala": NORTH_AMERICA,
    "haiti": NORTH_AMERICA,
    "honduras": NORTH_AMERICA,
    "jamaica": NORTH_AMERICA,
    "mexico": NORTH_AMERICA,
    "nicaragua": NORTH_AMERICA,
    "panama": NORTH_AMERICA,
    "saint kitts and nevis": NORTH_AMERICA,
    "saint lucia": NORTH_AMERICA,
    "saint vincent and the grenadines": NORTH_AMERICA,
    "trinidad and tobago": NORTH_AMERICA,
    "united states": NORTH_AMERICA,
    "united states of america": NORTH_AMERICA,
    "usa": NORTH_AMERICA,
    "us": NORTH_AMERICA,
    "u.s.": NORTH_AMERICA,
    "u.s.a.": NORTH_AMERICA,

    # South America
    "argentina": SOUTH_AMERICA,
    "bolivia": SOUTH_AMERICA,
    "brazil": SOUTH_AMERICA,
    "chile": SOUTH_AMERICA,
    "colombia": SOUTH_AMERICA,
    "ecuador": SOUTH_AMERICA,
    "guyana": SOUTH_AMERICA,
    "paraguay": SOUTH_AMERICA,
    "peru": SOUTH_AMERICA,
    "suriname": SOUTH_AMERICA,
    "uruguay": SOUTH_AMERICA,
    "venezuela": SOUTH_AMERICA,
}


def continent_for_country(country: str | None) -> str:
    """Best-effort continent lookup for a parsed country string. Falls back
    to OTHER rather than raising or dropping unrecognized values."""
    if not country:
        return OTHER
    return COUNTRY_TO_CONTINENT.get(country.strip().lower(), OTHER)
